services:
  - type: web
    name: attendance-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.headless true --server.port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
